import { useState } from "react";
import bullet from "../assets/Frame (11).png";
import { motion, AnimatePresence } from "framer-motion";

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

const faqs = [
  {
    question: "What is Anseru?",
    answer:
      "Anseru is a deal intelligence platform designed for enterprise sales teams. It helps companies respond to RFPs, security questionnaires, and compliance requests by turning past deal knowledge into structured, reusable intelligence."
  },
  {
    question: "How is Anseru different from traditional RFP tools?",
    answer:
      "Most RFP tools focus on storing answers or generating responses. Anseru focuses on understanding the deal context — including industry, compliance requirements, and prior responses — so teams don’t have to start from scratch each time."
  },
  {
    question: "Who is Anseru built for?",
    answer:
      "Anseru is built for teams involved in complex enterprise deals, including solutions engineering, security and compliance, and revenue operations. These teams typically collaborate to respond to procurement and due diligence requests."
  },
  {
    question: "How quickly can we start seeing value?",
    answer:
      "Teams typically see value within their first few deals. As more RFPs or security questionnaires are processed, Anseru begins reusing existing knowledge and reduces manual effort over time."
  },
  {
    question: "How accurate are the responses generated by Anseru?",
    answer:
      "Anseru combines AI-generated responses with validation layers such as source references, review workflows, and internal standards. This ensures responses are reliable, auditable, and aligned with company guidelines."
  },
  {
    question: "How does Anseru improve over time?",
    answer:
      "Anseru learns from every interaction, edit, approval, and past response captured across deals. This allows the system to continuously improve accuracy and relevance over time."
  },
  {
    question: "How does Anseru integrate with our existing tools?",
    answer:
      "Anseru is designed to work alongside your existing systems, including CRM platforms, document repositories, and collaboration tools. It pulls in relevant knowledge while allowing teams to continue working within familiar workflows."
  },
  {
    question: "How do you ensure our data is secure?",
    answer:
      "Anseru is built with enterprise-grade security in mind, including strict data isolation, access controls, and auditability. Customer data is handled within secure environments and protected according to compliance standards."
  },
  {
    question: "Do you use our data to train shared AI models?",
    answer:
      "No. Customer data is not used to train shared or public models. Each organization’s data remains isolated and is used only to improve its own responses and intelligence within the platform."
  }
];

  const leftColumn = faqs.slice(0, 5);
  const rightColumn = faqs.slice(5, 10);

  const FAQItem = ({ item, index }: { item: { question: string, answer: string }; index: number }) => {
    const isOpen = openIndex === index;
    return (
      <div className="flex flex-col border border-gray-100 bg-white rounded-sm overflow-hidden">
        <div
          className="flex items-center justify-between py-4 px-4 cursor-pointer hover:bg-gray-100 transition-all select-none"
          onClick={() => setOpenIndex(isOpen ? null : index)}
        >
          <div className="flex items-center gap-3">
            <img src={bullet} alt="" />
            <span className="text-[15px] text-black font-normal">{item.question}</span>
          </div>
          <span className="text-black text-lg leading-none ml-4 shrink-0 font-light">
            {isOpen ? "−" : "+"}
          </span>
        </div>

        <AnimatePresence initial={false}>
          {isOpen && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3, ease: [0.04, 0.62, 0.23, 0.98] }}
              className="overflow-hidden"
            >
              <div className="px-4 pb-4 pt-1 ml-7 mr-6">
                <p className="text-gray-600 text-sm leading-relaxed">
                  {item.answer}
                </p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    );
  };

  return (
    <section className="w-full py-16 md:py-24">
      <div className="max-w-[1400px] mx-auto px-6 md:px-12">
        {/* Header */}
        <div className="mb-10">
          <p className="anseru-section-tag">
            FAQs
          </p>
          <h2 className="anseru-section-title">
            Frequently Asked Questions
          </h2>
        </div>

        {/* Two-column grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {/* Left Column */}
          <div className="flex flex-col gap-3">
            {leftColumn.map((q, i) => (
              <FAQItem key={i} item={q} index={i} />
            ))}
          </div>

          {/* Right Column */}
          <div className="flex flex-col gap-3">
            {rightColumn.map((q, i) => (
              <FAQItem key={i + 5} item={q} index={i + 5} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
